require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmailSettingsController do

  # This should return the minimal set of attributes required to create a valid
  # EmailSetting. As you add validations to EmailSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmailSettingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all email_settings as @email_settings" do
      email_setting = EmailSetting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:email_settings).should eq([email_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested email_setting as @email_setting" do
      email_setting = EmailSetting.create! valid_attributes
      get :show, {:id => email_setting.to_param}, valid_session
      assigns(:email_setting).should eq(email_setting)
    end
  end

  describe "GET new" do
    it "assigns a new email_setting as @email_setting" do
      get :new, {}, valid_session
      assigns(:email_setting).should be_a_new(EmailSetting)
    end
  end

  describe "GET edit" do
    it "assigns the requested email_setting as @email_setting" do
      email_setting = EmailSetting.create! valid_attributes
      get :edit, {:id => email_setting.to_param}, valid_session
      assigns(:email_setting).should eq(email_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmailSetting" do
        expect {
          post :create, {:email_setting => valid_attributes}, valid_session
        }.to change(EmailSetting, :count).by(1)
      end

      it "assigns a newly created email_setting as @email_setting" do
        post :create, {:email_setting => valid_attributes}, valid_session
        assigns(:email_setting).should be_a(EmailSetting)
        assigns(:email_setting).should be_persisted
      end

      it "redirects to the created email_setting" do
        post :create, {:email_setting => valid_attributes}, valid_session
        response.should redirect_to(EmailSetting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved email_setting as @email_setting" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailSetting.any_instance.stub(:save).and_return(false)
        post :create, {:email_setting => { "user_id" => "invalid value" }}, valid_session
        assigns(:email_setting).should be_a_new(EmailSetting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailSetting.any_instance.stub(:save).and_return(false)
        post :create, {:email_setting => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested email_setting" do
        email_setting = EmailSetting.create! valid_attributes
        # Assuming there are no other email_settings in the database, this
        # specifies that the EmailSetting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmailSetting.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => email_setting.to_param, :email_setting => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested email_setting as @email_setting" do
        email_setting = EmailSetting.create! valid_attributes
        put :update, {:id => email_setting.to_param, :email_setting => valid_attributes}, valid_session
        assigns(:email_setting).should eq(email_setting)
      end

      it "redirects to the email_setting" do
        email_setting = EmailSetting.create! valid_attributes
        put :update, {:id => email_setting.to_param, :email_setting => valid_attributes}, valid_session
        response.should redirect_to(email_setting)
      end
    end

    describe "with invalid params" do
      it "assigns the email_setting as @email_setting" do
        email_setting = EmailSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailSetting.any_instance.stub(:save).and_return(false)
        put :update, {:id => email_setting.to_param, :email_setting => { "user_id" => "invalid value" }}, valid_session
        assigns(:email_setting).should eq(email_setting)
      end

      it "re-renders the 'edit' template" do
        email_setting = EmailSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailSetting.any_instance.stub(:save).and_return(false)
        put :update, {:id => email_setting.to_param, :email_setting => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested email_setting" do
      email_setting = EmailSetting.create! valid_attributes
      expect {
        delete :destroy, {:id => email_setting.to_param}, valid_session
      }.to change(EmailSetting, :count).by(-1)
    end

    it "redirects to the email_settings list" do
      email_setting = EmailSetting.create! valid_attributes
      delete :destroy, {:id => email_setting.to_param}, valid_session
      response.should redirect_to(email_settings_url)
    end
  end

end
